name: 🐛 Bug 回報
description: 建立一個 Bug 回報以協助我們改善專案
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        開立前，請先搜尋是否已有相同 Issue。
  - type: textarea
    id: what-happened
    attributes:
      label: 發生了什麼事？
      description: 請詳細描述您遇到的問題，以及您原本預期的結果。
      placeholder: 請告訴我們您看到了什麼...
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: 請提供問題重現的步驟：
      placeholder: "1. ...\n2. ..."
    validations:
      required: true
        
  - type: textarea
    id: logs
    attributes:
      label: 相關的 Log 記錄
      description: 請貼上任何相關的錯誤訊息或 Log。
      render: shell
